var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");void 0===window.centovacast&&(window.centovacast={});void 0===window.centovacast.options&&(window.centovacast.options={});
void 0===window.centovacast.loader&&(window.centovacast.loader={attempts:0,external_jquery:!1,loaded:!1,ready:!1,widget_definitions:{},url:"",load_script:function(a){var b=document.createElement("script");void 0!==b&&(b.setAttribute("type","text/javascript"),b.setAttribute("src",a),void 0!==b&&document.getElementsByTagName("head")[0].appendChild(b))},load_widget:function(a){a=this.widget_definitions[a];null===a.ref&&(a.ref=a.define(jQuery))},jq_loaded:function(){this.external_jquery||jQuery.noConflict();
jQuery.getJSONP=this.jq_get_jsonp;for(var a in this.widget_definitions)"string"===typeof a&&this.load_widget(a);this.loaded=!0;var b=this;jQuery(document).ready(function(){b.ready=!0;for(var a in b.widget_definitions)"function"===typeof b.widget_definitions[a].init&&b.widget_definitions[a].init(jQuery)})},check:function(){if("undefined"===typeof jQuery){var a=this;setTimeout(function(){a.check()},100);this.attempts++}else this.jq_loaded()},process_widget_element:function(a,b,c,d){a=jQuery(a);var e=
!1,f={},h;for(h in b)if(b.hasOwnProperty(h)){var g=b[h];var k=a.data(g);"undefined"!==typeof k?(f[g]=k,e=!0):f[g]=""}k=a.prop("id");if(e)f.type=a.data("type");else{if("string"!==typeof k||k.substr(0,c.length+1)!==c+"_")return null;f.fromid=!0;f.originalid=k;c=k.substr(c.length+1);if(d){d=/^([a-z0-9]+)_/;e=d.exec(c);if(!e)return null;f.type=e[1];c=c.replace(d,"")}var l=null;for(h in b)b.hasOwnProperty(h)&&(g=b[h],null===l&&(l=g),d=new RegExp("_"+h+"-([^_]+)"),e=d.exec(c))&&(f[g]=e[1],c=c.replace(d,
""));f[l]=c;"string"===typeof f.mount&&(f.mount=f.mount.replace(/-/,"/"))}f.id=k;f.$el=a;return f},process_widget_elements:function(a,b,c,d){var e={},f=this;a.each(function(){var a=f.process_widget_element(this,b,c,d),g=""+a.username+a.mount;e[g]||(e[g]=jQuery.extend({},a),d&&(e[g].type=void 0),e[g].hastype=d,e[g].$el=d?{}:null);d?e[g].$el[a.type]=e[g].$el[a.type]?e[g].$el[a.type].add(a.$el[0]):a.$el:e[g].$el=e[g].$el?e[g].$el.add(a.$el[0]):a.$el});return{widget_data:e,get:function(b){if(this.widget_data[b])return this.widget_data[b]},
get_property:function(b,a){if(this.widget_data[b]&&this.widget_data[b][a])return this.widget_data[b][a]},get_element:function(b,a){if(this.widget_data[b])return this.widget_data[b].hastype?this.widget_data[b].$el[a]?this.widget_data[b].$el[a]:jQuery():this.widget_data[b].$el?this.widget_data[b].$el:jQuery()},set_element:function(b,a,c){this.widget_data[b].hastype?a&&a.length&&(this.widget_data[b].$el[a]=c):this.widget_data[b].$el=c},set_property:function(b,a,c){if(!this.widget_data[b])return!1;this.widget_data[b][a]=
c;return!0},each:function(b){for(var a in this.widget_data)"string"===typeof a&&b(a,this.widget_data[a])},each_element:function(b,a){if(this.widget_data[b].hastype)for(var c in this.widget_data[b].$el)"string"!==typeof c&&void 0!==c||a(this.widget_data[b].$el[c],c);else a(this.widget_data[b].$el)}}},init:function(){var a=document.getElementsByTagName("script");a=a[a.length-1];a=void 0!==a.getAttribute.length?a.getAttribute("src"):a.getAttribute("src",2);a.match(/^https?:\/\//i)||(a=a.replace(/\/system\/.*$/,
"/"));this.url=a.replace(/(\.(?:[a-z]{2,}|[0-9]+)(:[0-9]+)?\/).*$/i,"$1");(this.external_jquery="undefined"!==typeof jQuery)||this.load_script(this.url+"system/jquery.min.js");this.check()},add:function(a,b,c){this.widget_definitions[a]||(this.widget_definitions[a]={define:c,init:b,ref:null});this.loaded&&this.load_widget(a);this.ready&&b(jQuery)},jq_get_jsonp:function(a,b,c){return jQuery.ajax({type:"GET",url:a,data:b,success:c,dataType:"jsonp"})}},window.centovacast.loader.init());
window.centovacast.loader.add("recenttracks",function(a){a.extend(window.centovacast.recenttracks.settings,window.centovacast.options.recenttracks);window.centovacast.recenttracks.run()},function(a){window.centovacast.options.recenttracks=a.extend({},window.centovacast.options.recenttracks,window.centovacast.recenttracks?window.centovacast.recenttracks.config:null);a("<link/>",{rel:"stylesheet",type:"text/css",href:window.centovacast.loader.url+"theme/widget_recenttracks.css"}).appendTo(a("body"));
return window.centovacast.recenttracks={pollcount:0,settings:{poll_limit:60,poll_frequency:6E4,track_limit:0,show_covers:1,scale_covers:1,buy_target:"_blank"},widgets:{},element_class:".cc_recenttracks_list",show_loading:function(b){b=this.widgets.get_element(b);var c=a("<div/>",{"class":"cc_recenttracks_throbber cctrack",css:{textAlign:"center",display:"none"},html:'<img src="'+window.centovacast.loader.url+'system/images/ajax-loading.gif" align="absmiddle" />'});c.appendTo(b);c.fadeIn("fast")},
clear_loading:function(b){this.widgets.get_element(b).find(".cc_recenttracks_throbber").remove()},demote_first:function(b){b=this.widgets.get_element(b);b=a(".cctrack:first",b);b.find(".cctitle").removeClass("ccnowplaying");b=b.find(".cctime");b.removeClass("ccnowplaying");b.html(b.data("timestr"))},create_new:function(b,c,d){var e=a("<div/>");e.addClass("cctrack");var f=a("<div/>");f.addClass("ccdetails");if(window.centovacast.recenttracks.settings.show_covers){var h=a("<div/>");h.addClass("cccover");
var g=a("<img/>",{src:b.image});d.w&&g.attr("width",d.w);d.h&&g.attr("height",d.h);g.appendTo(h);h.appendTo(e);f.addClass("ccdetails_withcover")}d=a("<div/>",{html:b.title});d.addClass("cctitle");c&&d.addClass("ccnowplaying");d.appendTo(f);d=a("<div/>",{html:b.artist});d.addClass("ccartist");d.appendTo(f);b.album&&(d=a("<div/>",{html:b.album}),d.addClass("ccalbum"),d.appendTo(f));b.url&&a("<div/>",{html:"<a class='ccbuy' "+(""!==window.centovacast.recenttracks.settings.buy_target?'target="'+window.centovacast.recenttracks.settings.buy_target+
'" ':"")+"href='"+b.url+"'>"+window.lang.buyalbum+"</a>"}).appendTo(f);d=!1;c&&window.centovacast.streaminfo&&window.centovacast.streaminfo.state&&(d=window.centovacast.streaminfo.state.serverstate&&window.centovacast.streaminfo.state.sourceconn);d=a("<div/>",{html:d?window.lang.nowplaying:b.localtime});d.addClass("cctime");c&&(d.data("timestr",b.localtime),d.addClass("ccnowplaying"));d.appendTo(e);f.appendTo(e);window.centovacast.recenttracks.settings.show_covers&&a("<div/>",{css:{clear:"both",fontSize:"0px",
height:"0"}}).appendTo(e);return e},slide_to_next:function(b,a){b.slideDown("slow",function(){window.centovacast.recenttracks.next(a)})},animate_next:function(b){var a=this.widgets.get(b),d=a.pending_tracks.pop();if(d){d.time>a.since&&this.widgets.set_property(b,"since",d.time);var e=this.widgets.get_element(b);this.demote_first(b);a=this.create_new(d,!0,a.options);a.hide();a.prependTo(e);this.slide_to_next(a,b)}},animate_element_next:function(){var b=a(this),c=b.data("ccwidgetid");"string"===typeof c&&
(b.remove(),window.centovacast.recenttracks.animate_next(c))},next:function(b){var c=this.widgets.get(b);if(c.pending_tracks.length){var d=this.widgets.get_element(b);a(".cctrack",d).length>=c.tracklimit?a(".cctrack:last",d).data("ccwidgetid",b).fadeOut("slow",this.animate_element_next):this.animate_next(b)}},handle_json:function(b,c){c||(c=b.rid);var d=this.widgets.get(c);if(d){var e=this.widgets.get_element(c);if("error"===b.type||b.data&&b.data.length&&1===b.data.length)d=b?b.error?b.error:b.data[0]:
"No JSON object",e.empty(),d=a("<div />",{html:'<span title="'+d+'">Unavailable</span>'}),d.addClass("cctrack"),d.appendTo(e),this.clear_loading(c);else{var f=b.data[0],h=b.data[1],g=b.data[2],k=this.settings.track_limit?this.settings.track_limit:b.data[3];b=b.data[4];h&&e.html("");if(h){window.lang||(window.lang={});window.lang.buyalbum=g[0];window.lang.nowplaying=g[1];window.lang.notracks=g[2];this.widgets.set_property(c,"tracklimit",k);this.widgets.set_property(c,"options",b);e.hide();for(h=0;h<
f.length;h++)e.append(this.create_new(f[h],0===h,b)),f[h].time>d.since&&this.widgets.set_property(c,"since",f[h].time);f.length||(d=a("<div/>"),d.addClass("cctrack"),d.append(window.lang.notracks).appendTo(e));e.fadeIn("def")}else this.widgets[c].set_property("pending_tracks",f),this.next(c)}}},poll:function(b){var c=this.widgets.get(b);this.show_loading(b);var d=(this.settings.local?"/":window.centovacast.loader.url)+"external/rpc.php";c={m:"recenttracks.get",username:c.username,charset:c.charset,
mountpoint:c.mount,rid:b};this.settings.track_limit&&(c.limit=this.settings.track_limit);var e=this;a.getJSONP(d,c,function(a){a&&e.handle_json(a,b)})},poll_all:function(){var a=this;this.widgets.each(function(b){a.poll(b)});(0===this.settings.poll_limit||this.pollcount++<this.settings.poll_limit)&&setTimeout(function(){a.poll_all()},this.settings.poll_frequency)},run:function(){this.widgets=window.centovacast.loader.process_widget_elements(a(this.element_class),{username:"username",cs:"charset",
mp:"mount"},"cc_recenttracks",!1);this.poll_all()}}});
