[[redirects]]
  from = "/*"
  to = "https://samuelpassamani.github.io/radio/example/example"
  status = 200
  force = true
    [redirects.headers]
    Access-Control-Allow-Origin = ""
    Access-Control-Allow-Headers = ""
    Access-Control-Allow-Methods = ""
    Access-Control-Allow-Credentials = ""
    Vary = ""
